/**
 * render.js — Reads CONFIG from config.js and builds the full biodata page.
 * Do NOT edit this file. Edit config.js only.
 */

(function () {

  /* ── HELPERS ────────────────────────────────────────────── */
  const infoItem = (icon, label, value) => `
    <div class="info-item">
      <div class="info-icon">${icon}</div>
      <div class="info-content">
        <div class="label">${label}</div>
        <div class="value">${value}</div>
      </div>
    </div>`;

  const divider = (icon, text) => `
    <div class="divider reveal reveal-delay-1">
      <div class="divider-icon">${icon}</div>
      <div class="divider-text">${text}</div>
      <div class="divider-icon">${icon}</div>
    </div>`;

  /* ── AGE CALC ────────────────────────────────────────────── */
  function calcAge(dobStr) {
    const dob = new Date(dobStr);
    if (isNaN(dob)) return '—';
    const today = new Date();
    let age = today.getFullYear() - dob.getFullYear();
    const m = today.getMonth() - dob.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < dob.getDate())) age--;
    return age;
  }

  /* ── DURATION CALC ───────────────────────────────────────── */
  function calcDuration(startStr, endStr) {
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    const parse   = s => { const [mo, y] = s.split(' '); return { y: parseInt(y), m: months.indexOf(mo) }; };
    if (!startStr) return '';
    const s = parse(startStr);
    const e = endStr ? parse(endStr) : { y: new Date().getFullYear(), m: new Date().getMonth() };
    let total = (e.y - s.y) * 12 + (e.m - s.m);
    if (total < 0) total = 0;
    const yrs = Math.floor(total / 12);
    const mos = total % 12;
    const parts = [];
    if (yrs > 0) parts.push(`${yrs} yr${yrs > 1 ? 's' : ''}`);
    if (mos > 0) parts.push(`${mos} month${mos > 1 ? 's' : ''}`);
    return parts.length ? parts.join(' ') : 'Less than a month';
  }

  /* ── SIBLING RENDERER ────────────────────────────────────── */
  function renderSibling(s) {
    const icon    = s.type === 'brother' ? '👦' : '👧';
    const typeStr = s.type === 'brother' ? 'Brother' : 'Sister';
    let detail = `💼 ${s.job}`;
    if (s.company)        detail += ` at ${s.company}`;
    if (s.employmentType) detail += ` (${s.employmentType})`;
    if (s.maritalStatus === 'Married' && s.spouseName) {
      detail += `<br/>💍 Married to <strong>${s.spouseName}</strong>`;
      if (s.spouseJob)     detail += ` · ${s.spouseJob}`;
      if (s.spouseCompany) detail += ` at ${s.spouseCompany}`;
    }
    return `
      <div class="member">
        <div class="member-icon">${icon}</div>
        <div class="member-info">
          <div class="role">${typeStr} · ${s.maritalStatus}</div>
          <div class="name">${s.name}</div>
          <div class="detail">${detail}</div>
        </div>
      </div>`;
  }

  /* ── MAIN BUILD ──────────────────────────────────────────── */
  function build() {
    const C   = CONFIG;
    const age = calcAge(C.dob);
    const app = document.getElementById('app');

    app.innerHTML = `

      <!-- HERO -->
      <div class="hero">
        <div class="hero-banner">
          <div class="hero-tagline">🕉 વિવાહ પરિચય • Vivah Parichay 🕉</div>
          <div class="hero-title">A Journey Towards<br/>A Beautiful Union</div>
          <div class="hero-subtitle">— Biodata of ${C.name} —</div>
        </div>
        <div class="profile-float">
          <div class="profile-ring" onclick="openModal()" title="Click to view photos">
            <img class="profile-img" src="profile.jpg" alt="${C.name} profile photo" />
          </div>
          <div class="profile-badge">✦ Tap to View ✦</div>
        </div>
        <div class="profile-name">
          <h1>${C.name}</h1>
          <div class="guj-name">${C.nameGujarati}</div>
          <div class="gotra-tag">💼 ${C.jobs[0].title} · ${C.jobs[0].company}</div>
        </div>
      </div>

      <!-- STATS -->
      <div class="ornament">❁ ❁ ❁</div>
      <div class="stats-strip reveal">
        <div class="stat-pill"><div class="stat-val">${age}</div><div class="stat-label">Age (Yrs)</div></div>
        <div class="stat-pill"><div class="stat-val">${C.height}</div><div class="stat-label">Height</div></div>
        <div class="stat-pill"><div class="stat-val">${C.weight}</div><div class="stat-label">Weight (kg)</div></div>
        <div class="stat-pill"><div class="stat-val">${C.jobExperience}</div><div class="stat-label">Job Experience</div></div>
      </div>

      <!-- PERSONAL DETAILS -->
      ${divider('🌸', 'Personal Details')}
      <div class="card reveal">
        <div class="info-grid">
          ${infoItem('🎂', 'Date of Birth', new Date(C.dob).toLocaleDateString('en-IN', {day:'numeric',month:'long',year:'numeric'}))}
          ${infoItem('⚖️', 'Height & Weight', `${C.height} • ${C.weight} kg`)}
          ${infoItem('🩸', 'Blood Group', C.bloodGroup)}
          ${infoItem('🏡', 'Native Village', C.nativeVillage)}
          ${infoItem('📍', 'Current City', C.currentCity)}
          ${infoItem('🛕', 'Religion & Caste', `${C.religion} • ${C.casteDetail}`)}
        </div>
      </div>

      <!-- FAMILY -->
      ${divider('🏠', 'Family Details')}
      <div class="two-col reveal">
        <div class="family-box">
          <h3>👴 Paternal Family (Father's Side)</h3>
          <div class="member">
            <div class="member-icon">👨</div>
            <div class="member-info"><div class="role">Father</div><div class="name">${C.fatherName}</div></div>
          </div>
          <div class="member">
            <div class="member-icon">👩</div>
            <div class="member-info"><div class="role">Mother</div><div class="name">${C.motherName}</div></div>
          </div>
          <div class="member">
            <div class="member-icon">💼</div>
            <div class="member-info"><div class="role">Father's Occupation</div><div class="name">${C.fatherOccupation}</div></div>
          </div>
          <div class="member">
            <div class="member-icon">🏡</div>
            <div class="member-info"><div class="role">Village</div><div class="name">${C.fatherVillage}</div></div>
          </div>
          ${C.siblings.map(renderSibling).join('')}
        </div>
        <div class="family-box">
          <h3>👵 Maternal Family (Mama's Side)</h3>
          <div class="member">
            <div class="member-icon">👨</div>
            <div class="member-info"><div class="role">Maternal Grandfather (Nana)</div><div class="name">${C.nanaName}</div></div>
          </div>
          <div class="member">
            <div class="member-icon">👩</div>
            <div class="member-info"><div class="role">Maternal Grandmother (Nani)</div><div class="name">${C.naniName}</div></div>
          </div>
          <div class="member">
            <div class="member-icon">👨‍💼</div>
            <div class="member-info"><div class="role">Mama (Uncle)</div><div class="name">${C.mamaName}</div></div>
          </div>
          <div class="member">
            <div class="member-icon">🏡</div>
            <div class="member-info"><div class="role">Maternal Village</div><div class="name">${C.mamaVillage}</div></div>
          </div>
          <div class="member">
            <div class="member-icon">🏢</div>
            <div class="member-info"><div class="role">Mama's Occupation</div><div class="name">${C.mamaOccupation}</div></div>
          </div>
        </div>
      </div>

      <!-- EDUCATION -->
      ${divider('🎓', 'Education')}
      <div class="card reveal">
        <div class="info-grid">
          ${infoItem('🎓', 'Highest Qualification', C.degree)}
          ${infoItem('🏫', 'College / University', C.college)}
          ${infoItem('📅', 'Year of Passing', C.yearOfPassing)}
          ${infoItem('📊', 'Percentage / CGPA', C.percentage)}
          ${infoItem('🗣️', 'Languages Known', C.languages)}
        </div>
      </div>

      <!-- CAREER -->
      ${divider('💼', 'Career & Profession')}
      <div class="card reveal">
        <div class="career-timeline">
          ${C.jobs.map(j => `
            <div class="career-item">
              <div class="ci-title">${j.title}</div>
              <div class="ci-company">🏢 ${j.company} · ${j.city}</div>
              ${j.startDate ? `<div class="ci-duration">🗓️ ${j.startDate} – ${j.isCurrent ? '<span style="color:var(--gold-dark);font-weight:600;">Currently Working</span>' : (j.endDate || '')}</div>` : ''}
              ${!j.isCurrent && j.startDate ? `<div class="duration-tag">⏱️ ${calcDuration(j.startDate, j.endDate)}</div>` : ''}
              <div class="ci-desc">${j.description}</div>
              ${j.isCurrent ? `<div class="salary-tag">💰 CTC: ${j.ctc}</div>` : ''}
            </div>`).join('')}
        </div>
      </div>

      <!-- HOBBIES -->
      ${divider('🎯', 'Hobbies & Lifestyle')}
      <div class="card reveal">
        <div class="hobby-pills">
          ${C.hobbies.map(h => `<div class="hobby-pill">${h.emoji} ${h.label}</div>`).join('')}
        </div>
        <div style="margin-top:24px;">
          <div class="info-grid">
            ${infoItem('🚬', 'Smoking / Drinking', `${C.smoking} / ${C.drinking}`)}
          </div>
        </div>
      </div>

      <!-- CONTACT -->
      ${divider('💌', 'Get in Touch')}
      <div class="contact-card reveal">
        <h2>Let's Connect 🙏</h2>
        <p>Reach out to discuss further. We would love to hear from you.</p>
        <div class="contact-btns">
          <a id="btn-whatsapp" class="contact-btn primary" href="https://wa.me/${C.whatsappNumber}" target="_blank" rel="noopener">💬 WhatsApp</a>
          <a id="btn-call"     class="contact-btn secondary" href="tel:${C.whatsappNumber}">📞 Call Us</a>
          <a id="btn-email"    class="contact-btn secondary" href="mailto:${C.email}">✉️ Email</a>
        </div>
        <div class="contact-info-list">
          <div class="contact-info-item"><span>👨</span><span><strong>${C.fatherName}</strong> (Father) – ${C.fatherPhone}</span></div>
          <div class="contact-info-item"><span>📍</span><span>${C.contactCity}</span></div>
        </div>
      </div>

      <!-- FOOTER -->
      <div class="footer reveal">
        <div class="jai">🕉 જય શ્રી કૃષ્ણ 🕉</div>
        <div>Made with ❤️ by ${C.name} • This biodata is strictly for matrimonial purposes.</div>
        <div style="margin-top:6px; color:var(--gold-dark); font-weight:600;">Powered by AntiGravity ✦</div>
      </div>
    `;

    /* ── SCROLL REVEAL ───────────────────────────────────── */
    const revealEls = document.querySelectorAll('.reveal');
    const obs = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target); }
      });
    }, { threshold: 0.1 });
    revealEls.forEach(e => obs.observe(e));

    document.title = `Vivah Parichay – ${C.name} | Marriage Biodata`;
  }

  /* ── MODAL CAROUSEL ──────────────────────────────────────── */
  let mIdx    = 0;
  let mSlides = [];
  let mDots   = [];

  function allPhotos() {
    return (CONFIG.photos && CONFIG.photos.length) ? CONFIG.photos : ['profile.jpg'];
  }

  function buildModal() {
    const photos = allPhotos();
    const track  = document.getElementById('modalTrack');
    const dotsEl = document.getElementById('modalDots');
    track.innerHTML  = '';
    dotsEl.innerHTML = '';
    mSlides = [];
    mDots   = [];

    photos.forEach((src, i) => {
      /* slide */
      const div = document.createElement('div');
      div.className = 'mc-slide';
      const img = document.createElement('img');
      img.src = src;
      img.alt = `Photo ${i + 1}`;
      div.appendChild(img);
      div.addEventListener('click', () => {
        const n = photos.length;
        const rel = ((i - mIdx) + n) % n;
        if (rel === n - 1) mNav(-1);
        else if (rel === 1) mNav(1);
        /* center click does nothing */
      });
      track.appendChild(div);
      mSlides.push(div);

      /* dot */
      const dot = document.createElement('span');
      dot.className = 'modal-dot';
      dot.addEventListener('click', e => { e.stopPropagation(); mGoTo(i); });
      dotsEl.appendChild(dot);
      mDots.push(dot);
    });
  }

  function mRefresh() {
    const n = mSlides.length;
    mSlides.forEach((s, i) => {
      const rel = ((i - mIdx) + n) % n;
      s.className = 'mc-slide ' + (
        rel === 0     ? 'mc-center' :
        rel === 1     ? 'mc-next'   :
        rel === n - 1 ? 'mc-prev'   : 'mc-hidden'
      );
    });
    mDots.forEach((d, i) => d.classList.toggle('active', i === mIdx));
  }

  function mGoTo(i) {
    const n = mSlides.length;
    mIdx = ((i % n) + n) % n;
    mRefresh();
  }

  function mNav(dir) { mGoTo(mIdx + dir); }
  window.modalNav = mNav;

  window.openModal = () => {
    const photos = allPhotos();
    /* start at profile.jpg if found, else index 0 */
    const pi = photos.findIndex(p => p.toLowerCase().includes('profile'));
    mIdx = pi >= 0 ? pi : 0;
    buildModal();
    mRefresh();
    document.getElementById('photoModal').classList.add('open');
    document.body.style.overflow = 'hidden';
  };

  window.closeModal = () => {
    document.getElementById('photoModal').classList.remove('open');
    document.body.style.overflow = '';
  };

  /* swipe on modal track */
  document.addEventListener('DOMContentLoaded', () => {
    let tx = 0;
    const track = document.getElementById('modalTrack');
    if (track) {
      track.addEventListener('touchstart', e => { tx = e.touches[0].clientX; }, { passive: true });
      track.addEventListener('touchend',   e => {
        const dx = e.changedTouches[0].clientX - tx;
        if (Math.abs(dx) > 50) dx < 0 ? mNav(1) : mNav(-1);
      });
    }
  });

  /* keyboard */
  document.addEventListener('keydown', e => {
    if (!document.getElementById('photoModal').classList.contains('open')) return;
    if (e.key === 'Escape')     window.closeModal();
    if (e.key === 'ArrowLeft')  mNav(-1);
    if (e.key === 'ArrowRight') mNav(1);
  });

  /* ── KICK OFF ────────────────────────────────────────────── */
  build();

})();
